// Runtime accessor for the bundled Steam capsule manifest. Mirrors the
// shape of apps/web/src/lol/_shared/asset-manifest.ts: a slim presence set
// generated by the refresh script, with paths derived at the call site.
import { steamCapsuleAppids } from "./manifest.gen";

export function getSteamCapsuleAsset(appid: number): string | undefined {
  return steamCapsuleAppids.has(appid) ? `/steam/apps/${appid}/capsule.webp` : undefined;
}
