-- AlterTable
ALTER TABLE "Match" ADD COLUMN     "csAt10" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "csAt15" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "deathTimings" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "goldAt10" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "goldAt15" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "teamGoldDiffAt15" INTEGER NOT NULL DEFAULT 0;
