import { describe, expect, it } from "vitest";
import {
  getChampionAsset,
  getItemAsset,
  getRoleIconAsset,
  getRuneAsset,
  getSummonerSpellAsset,
  normalizeChampionAlias,
} from "./asset-manifest";
import {
  championBackdropSplashUrl,
  championCardSplashUrl,
  championSquareIconUrl,
  itemIconUrl,
} from "./champion-icon";
import { roleIconUrl } from "./role-icon";

// These tests pin the manifest-first behaviour of the URL helpers. They
// assume manifest.json was generated by scripts/refresh-lol-assets.mts and
// contains a representative coverage of the asset universe; the chosen
// fixtures (Lux, Ahri, item 1001, etc.) are well-known stable keys.

describe("normalizeChampionAlias", () => {
  it("strips the Strawberry_ Swarm-mode prefix", () => {
    expect(normalizeChampionAlias("Strawberry_Yasuo")).toBe("Yasuo");
  });

  it("passes through aliases without the prefix", () => {
    expect(normalizeChampionAlias("Lux")).toBe("Lux");
  });
});

describe("asset-manifest lookups", () => {
  it("resolves a known champion across all three variants", () => {
    expect(getChampionAsset("Lux", "square")).toBe("/lol/champions/Lux/square.webp");
    expect(getChampionAsset("Lux", "card")).toBe("/lol/champions/Lux/card.webp");
    expect(getChampionAsset("Lux", "backdrop")).toBe("/lol/champions/Lux/backdrop.webp");
  });

  it("normalises Swarm aliases before lookup", () => {
    expect(getChampionAsset("Strawberry_Lux", "square")).toBe(
      "/lol/champions/Lux/square.webp"
    );
  });

  it("returns undefined for unknown champion", () => {
    expect(getChampionAsset("NotARealChampion", "square")).toBeUndefined();
  });

  it("resolves a known item by numeric and string id", () => {
    expect(getItemAsset(1001)).toBe("/lol/items/1001.webp");
    expect(getItemAsset("1001")).toBe("/lol/items/1001.webp");
  });

  it("resolves runes and summoner spells from manifest", () => {
    // 8005 is the Press the Attack keystone — stable id.
    expect(getRuneAsset(8005)).toBe("/lol/runes/8005.webp");
    // Summoner spell 4 = Flash.
    expect(getSummonerSpellAsset(4)).toBe("/lol/summoner-spells/4.webp");
  });

  it("resolves role icons by slug", () => {
    expect(getRoleIconAsset("top")).toBe("/lol/role-icons/position-top.svg");
    expect(getRoleIconAsset("utility")).toBe("/lol/role-icons/position-utility.svg");
  });
});

describe("URL helpers prefer the manifest", () => {
  it("championSquareIconUrl returns the bundled path for known champions", () => {
    expect(championSquareIconUrl("Lux")).toBe("/lol/champions/Lux/square.webp");
  });

  it("championCardSplashUrl returns the bundled card", () => {
    expect(championCardSplashUrl("Ahri")).toBe("/lol/champions/Ahri/card.webp");
  });

  it("championBackdropSplashUrl returns the bundled backdrop", () => {
    expect(championBackdropSplashUrl("Ahri")).toBe("/lol/champions/Ahri/backdrop.webp");
  });

  it("itemIconUrl prefers the bundled WebP over the DDragon PNG", () => {
    expect(itemIconUrl(1001, "16.10.1")).toBe("/lol/items/1001.webp");
  });

  it("roleIconUrl prefers the bundled SVG", () => {
    expect(roleIconUrl("TOP")).toBe("/lol/role-icons/position-top.svg");
  });

  it("falls back to a remote URL when the manifest has no entry", () => {
    const url = championSquareIconUrl("NotARealChampion");
    expect(url.startsWith("https://wsrv.nl/")).toBe(true);
    expect(url).toContain("notarealchampion");
  });
});
