/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SteamRouteImport } from './routes/steam'
import { Route as StatusRouteImport } from './routes/status'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SteamIndexRouteImport } from './routes/steam/index'
import { Route as LolIndexRouteImport } from './routes/lol/index'
import { Route as SteamWishlistRouteImport } from './routes/steam/wishlist'
import { Route as SteamLibraryRouteImport } from './routes/steam/library'
import { Route as SteamAchievementsRouteImport } from './routes/steam/achievements'
import { Route as LolAccountSlugRouteImport } from './routes/lol/$accountSlug'
import { Route as LolAccountSlugIndexRouteImport } from './routes/lol/$accountSlug/index'
import { Route as SteamGameAppidRouteImport } from './routes/steam/game.$appid'
import { Route as SteamAchievementsSignatureRouteImport } from './routes/steam/achievements_.signature'
import { Route as LolAccountSlugTrendsRouteImport } from './routes/lol/$accountSlug/trends'
import { Route as LolAccountSlugRecapRouteImport } from './routes/lol/$accountSlug/recap'
import { Route as LolAccountSlugLiveRouteImport } from './routes/lol/$accountSlug/live'
import { Route as LolAccountSlugPatchesIndexRouteImport } from './routes/lol/$accountSlug/patches/index'
import { Route as LolAccountSlugMatchesIndexRouteImport } from './routes/lol/$accountSlug/matches/index'
import { Route as LolAccountSlugChampionsIndexRouteImport } from './routes/lol/$accountSlug/champions/index'
import { Route as LolAccountSlugPatchesVersionRouteImport } from './routes/lol/$accountSlug/patches/$version'
import { Route as LolAccountSlugMatchesMatchIdRouteImport } from './routes/lol/$accountSlug/matches/$matchId'
import { Route as LolAccountSlugChampionsChampionKeyRouteImport } from './routes/lol/$accountSlug/champions/$championKey'
import { Route as LolAccountSlugMatchesMatchIdIndexRouteImport } from './routes/lol/$accountSlug/matches/$matchId/index'
import { Route as LolAccountSlugMatchesMatchIdYourGameRouteImport } from './routes/lol/$accountSlug/matches/$matchId/your-game'
import { Route as LolAccountSlugMatchesMatchIdTimelineRouteImport } from './routes/lol/$accountSlug/matches/$matchId/timeline'
import { Route as LolAccountSlugMatchesMatchIdRecapRouteImport } from './routes/lol/$accountSlug/matches/$matchId/recap'

const SteamRoute = SteamRouteImport.update({
  id: '/steam',
  path: '/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SteamIndexRoute = SteamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SteamRoute,
} as any)
const LolIndexRoute = LolIndexRouteImport.update({
  id: '/lol/',
  path: '/lol/',
  getParentRoute: () => rootRouteImport,
} as any)
const SteamWishlistRoute = SteamWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SteamRoute,
} as any)
const SteamLibraryRoute = SteamLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => SteamRoute,
} as any)
const SteamAchievementsRoute = SteamAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => SteamRoute,
} as any)
const LolAccountSlugRoute = LolAccountSlugRouteImport.update({
  id: '/lol/$accountSlug',
  path: '/lol/$accountSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LolAccountSlugIndexRoute = LolAccountSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const SteamGameAppidRoute = SteamGameAppidRouteImport.update({
  id: '/game/$appid',
  path: '/game/$appid',
  getParentRoute: () => SteamRoute,
} as any)
const SteamAchievementsSignatureRoute =
  SteamAchievementsSignatureRouteImport.update({
    id: '/achievements_/signature',
    path: '/achievements/signature',
    getParentRoute: () => SteamRoute,
  } as any)
const LolAccountSlugTrendsRoute = LolAccountSlugTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const LolAccountSlugRecapRoute = LolAccountSlugRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const LolAccountSlugLiveRoute = LolAccountSlugLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const LolAccountSlugPatchesIndexRoute =
  LolAccountSlugPatchesIndexRouteImport.update({
    id: '/patches/',
    path: '/patches/',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugMatchesIndexRoute =
  LolAccountSlugMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugChampionsIndexRoute =
  LolAccountSlugChampionsIndexRouteImport.update({
    id: '/champions/',
    path: '/champions/',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugPatchesVersionRoute =
  LolAccountSlugPatchesVersionRouteImport.update({
    id: '/patches/$version',
    path: '/patches/$version',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugMatchesMatchIdRoute =
  LolAccountSlugMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugChampionsChampionKeyRoute =
  LolAccountSlugChampionsChampionKeyRouteImport.update({
    id: '/champions/$championKey',
    path: '/champions/$championKey',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugMatchesMatchIdIndexRoute =
  LolAccountSlugMatchesMatchIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LolAccountSlugMatchesMatchIdRoute,
  } as any)
const LolAccountSlugMatchesMatchIdYourGameRoute =
  LolAccountSlugMatchesMatchIdYourGameRouteImport.update({
    id: '/your-game',
    path: '/your-game',
    getParentRoute: () => LolAccountSlugMatchesMatchIdRoute,
  } as any)
const LolAccountSlugMatchesMatchIdTimelineRoute =
  LolAccountSlugMatchesMatchIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => LolAccountSlugMatchesMatchIdRoute,
  } as any)
const LolAccountSlugMatchesMatchIdRecapRoute =
  LolAccountSlugMatchesMatchIdRecapRouteImport.update({
    id: '/recap',
    path: '/recap',
    getParentRoute: () => LolAccountSlugMatchesMatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/steam': typeof SteamRouteWithChildren
  '/lol/$accountSlug': typeof LolAccountSlugRouteWithChildren
  '/steam/achievements': typeof SteamAchievementsRoute
  '/steam/library': typeof SteamLibraryRoute
  '/steam/wishlist': typeof SteamWishlistRoute
  '/lol/': typeof LolIndexRoute
  '/steam/': typeof SteamIndexRoute
  '/lol/$accountSlug/live': typeof LolAccountSlugLiveRoute
  '/lol/$accountSlug/recap': typeof LolAccountSlugRecapRoute
  '/lol/$accountSlug/trends': typeof LolAccountSlugTrendsRoute
  '/steam/achievements/signature': typeof SteamAchievementsSignatureRoute
  '/steam/game/$appid': typeof SteamGameAppidRoute
  '/lol/$accountSlug/': typeof LolAccountSlugIndexRoute
  '/lol/$accountSlug/champions/$championKey': typeof LolAccountSlugChampionsChampionKeyRoute
  '/lol/$accountSlug/matches/$matchId': typeof LolAccountSlugMatchesMatchIdRouteWithChildren
  '/lol/$accountSlug/patches/$version': typeof LolAccountSlugPatchesVersionRoute
  '/lol/$accountSlug/champions/': typeof LolAccountSlugChampionsIndexRoute
  '/lol/$accountSlug/matches/': typeof LolAccountSlugMatchesIndexRoute
  '/lol/$accountSlug/patches/': typeof LolAccountSlugPatchesIndexRoute
  '/lol/$accountSlug/matches/$matchId/recap': typeof LolAccountSlugMatchesMatchIdRecapRoute
  '/lol/$accountSlug/matches/$matchId/timeline': typeof LolAccountSlugMatchesMatchIdTimelineRoute
  '/lol/$accountSlug/matches/$matchId/your-game': typeof LolAccountSlugMatchesMatchIdYourGameRoute
  '/lol/$accountSlug/matches/$matchId/': typeof LolAccountSlugMatchesMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/steam/achievements': typeof SteamAchievementsRoute
  '/steam/library': typeof SteamLibraryRoute
  '/steam/wishlist': typeof SteamWishlistRoute
  '/lol': typeof LolIndexRoute
  '/steam': typeof SteamIndexRoute
  '/lol/$accountSlug/live': typeof LolAccountSlugLiveRoute
  '/lol/$accountSlug/recap': typeof LolAccountSlugRecapRoute
  '/lol/$accountSlug/trends': typeof LolAccountSlugTrendsRoute
  '/steam/achievements/signature': typeof SteamAchievementsSignatureRoute
  '/steam/game/$appid': typeof SteamGameAppidRoute
  '/lol/$accountSlug': typeof LolAccountSlugIndexRoute
  '/lol/$accountSlug/champions/$championKey': typeof LolAccountSlugChampionsChampionKeyRoute
  '/lol/$accountSlug/patches/$version': typeof LolAccountSlugPatchesVersionRoute
  '/lol/$accountSlug/champions': typeof LolAccountSlugChampionsIndexRoute
  '/lol/$accountSlug/matches': typeof LolAccountSlugMatchesIndexRoute
  '/lol/$accountSlug/patches': typeof LolAccountSlugPatchesIndexRoute
  '/lol/$accountSlug/matches/$matchId/recap': typeof LolAccountSlugMatchesMatchIdRecapRoute
  '/lol/$accountSlug/matches/$matchId/timeline': typeof LolAccountSlugMatchesMatchIdTimelineRoute
  '/lol/$accountSlug/matches/$matchId/your-game': typeof LolAccountSlugMatchesMatchIdYourGameRoute
  '/lol/$accountSlug/matches/$matchId': typeof LolAccountSlugMatchesMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/status': typeof StatusRoute
  '/steam': typeof SteamRouteWithChildren
  '/lol/$accountSlug': typeof LolAccountSlugRouteWithChildren
  '/steam/achievements': typeof SteamAchievementsRoute
  '/steam/library': typeof SteamLibraryRoute
  '/steam/wishlist': typeof SteamWishlistRoute
  '/lol/': typeof LolIndexRoute
  '/steam/': typeof SteamIndexRoute
  '/lol/$accountSlug/live': typeof LolAccountSlugLiveRoute
  '/lol/$accountSlug/recap': typeof LolAccountSlugRecapRoute
  '/lol/$accountSlug/trends': typeof LolAccountSlugTrendsRoute
  '/steam/achievements_/signature': typeof SteamAchievementsSignatureRoute
  '/steam/game/$appid': typeof SteamGameAppidRoute
  '/lol/$accountSlug/': typeof LolAccountSlugIndexRoute
  '/lol/$accountSlug/champions/$championKey': typeof LolAccountSlugChampionsChampionKeyRoute
  '/lol/$accountSlug/matches/$matchId': typeof LolAccountSlugMatchesMatchIdRouteWithChildren
  '/lol/$accountSlug/patches/$version': typeof LolAccountSlugPatchesVersionRoute
  '/lol/$accountSlug/champions/': typeof LolAccountSlugChampionsIndexRoute
  '/lol/$accountSlug/matches/': typeof LolAccountSlugMatchesIndexRoute
  '/lol/$accountSlug/patches/': typeof LolAccountSlugPatchesIndexRoute
  '/lol/$accountSlug/matches/$matchId/recap': typeof LolAccountSlugMatchesMatchIdRecapRoute
  '/lol/$accountSlug/matches/$matchId/timeline': typeof LolAccountSlugMatchesMatchIdTimelineRoute
  '/lol/$accountSlug/matches/$matchId/your-game': typeof LolAccountSlugMatchesMatchIdYourGameRoute
  '/lol/$accountSlug/matches/$matchId/': typeof LolAccountSlugMatchesMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/status'
    | '/steam'
    | '/lol/$accountSlug'
    | '/steam/achievements'
    | '/steam/library'
    | '/steam/wishlist'
    | '/lol/'
    | '/steam/'
    | '/lol/$accountSlug/live'
    | '/lol/$accountSlug/recap'
    | '/lol/$accountSlug/trends'
    | '/steam/achievements/signature'
    | '/steam/game/$appid'
    | '/lol/$accountSlug/'
    | '/lol/$accountSlug/champions/$championKey'
    | '/lol/$accountSlug/matches/$matchId'
    | '/lol/$accountSlug/patches/$version'
    | '/lol/$accountSlug/champions/'
    | '/lol/$accountSlug/matches/'
    | '/lol/$accountSlug/patches/'
    | '/lol/$accountSlug/matches/$matchId/recap'
    | '/lol/$accountSlug/matches/$matchId/timeline'
    | '/lol/$accountSlug/matches/$matchId/your-game'
    | '/lol/$accountSlug/matches/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/status'
    | '/steam/achievements'
    | '/steam/library'
    | '/steam/wishlist'
    | '/lol'
    | '/steam'
    | '/lol/$accountSlug/live'
    | '/lol/$accountSlug/recap'
    | '/lol/$accountSlug/trends'
    | '/steam/achievements/signature'
    | '/steam/game/$appid'
    | '/lol/$accountSlug'
    | '/lol/$accountSlug/champions/$championKey'
    | '/lol/$accountSlug/patches/$version'
    | '/lol/$accountSlug/champions'
    | '/lol/$accountSlug/matches'
    | '/lol/$accountSlug/patches'
    | '/lol/$accountSlug/matches/$matchId/recap'
    | '/lol/$accountSlug/matches/$matchId/timeline'
    | '/lol/$accountSlug/matches/$matchId/your-game'
    | '/lol/$accountSlug/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/status'
    | '/steam'
    | '/lol/$accountSlug'
    | '/steam/achievements'
    | '/steam/library'
    | '/steam/wishlist'
    | '/lol/'
    | '/steam/'
    | '/lol/$accountSlug/live'
    | '/lol/$accountSlug/recap'
    | '/lol/$accountSlug/trends'
    | '/steam/achievements_/signature'
    | '/steam/game/$appid'
    | '/lol/$accountSlug/'
    | '/lol/$accountSlug/champions/$championKey'
    | '/lol/$accountSlug/matches/$matchId'
    | '/lol/$accountSlug/patches/$version'
    | '/lol/$accountSlug/champions/'
    | '/lol/$accountSlug/matches/'
    | '/lol/$accountSlug/patches/'
    | '/lol/$accountSlug/matches/$matchId/recap'
    | '/lol/$accountSlug/matches/$matchId/timeline'
    | '/lol/$accountSlug/matches/$matchId/your-game'
    | '/lol/$accountSlug/matches/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatusRoute: typeof StatusRoute
  SteamRoute: typeof SteamRouteWithChildren
  LolAccountSlugRoute: typeof LolAccountSlugRouteWithChildren
  LolIndexRoute: typeof LolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/steam': {
      id: '/steam'
      path: '/steam'
      fullPath: '/steam'
      preLoaderRoute: typeof SteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steam/': {
      id: '/steam/'
      path: '/'
      fullPath: '/steam/'
      preLoaderRoute: typeof SteamIndexRouteImport
      parentRoute: typeof SteamRoute
    }
    '/lol/': {
      id: '/lol/'
      path: '/lol'
      fullPath: '/lol/'
      preLoaderRoute: typeof LolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steam/wishlist': {
      id: '/steam/wishlist'
      path: '/wishlist'
      fullPath: '/steam/wishlist'
      preLoaderRoute: typeof SteamWishlistRouteImport
      parentRoute: typeof SteamRoute
    }
    '/steam/library': {
      id: '/steam/library'
      path: '/library'
      fullPath: '/steam/library'
      preLoaderRoute: typeof SteamLibraryRouteImport
      parentRoute: typeof SteamRoute
    }
    '/steam/achievements': {
      id: '/steam/achievements'
      path: '/achievements'
      fullPath: '/steam/achievements'
      preLoaderRoute: typeof SteamAchievementsRouteImport
      parentRoute: typeof SteamRoute
    }
    '/lol/$accountSlug': {
      id: '/lol/$accountSlug'
      path: '/lol/$accountSlug'
      fullPath: '/lol/$accountSlug'
      preLoaderRoute: typeof LolAccountSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/$accountSlug/': {
      id: '/lol/$accountSlug/'
      path: '/'
      fullPath: '/lol/$accountSlug/'
      preLoaderRoute: typeof LolAccountSlugIndexRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/steam/game/$appid': {
      id: '/steam/game/$appid'
      path: '/game/$appid'
      fullPath: '/steam/game/$appid'
      preLoaderRoute: typeof SteamGameAppidRouteImport
      parentRoute: typeof SteamRoute
    }
    '/steam/achievements_/signature': {
      id: '/steam/achievements_/signature'
      path: '/achievements/signature'
      fullPath: '/steam/achievements/signature'
      preLoaderRoute: typeof SteamAchievementsSignatureRouteImport
      parentRoute: typeof SteamRoute
    }
    '/lol/$accountSlug/trends': {
      id: '/lol/$accountSlug/trends'
      path: '/trends'
      fullPath: '/lol/$accountSlug/trends'
      preLoaderRoute: typeof LolAccountSlugTrendsRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/recap': {
      id: '/lol/$accountSlug/recap'
      path: '/recap'
      fullPath: '/lol/$accountSlug/recap'
      preLoaderRoute: typeof LolAccountSlugRecapRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/live': {
      id: '/lol/$accountSlug/live'
      path: '/live'
      fullPath: '/lol/$accountSlug/live'
      preLoaderRoute: typeof LolAccountSlugLiveRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/patches/': {
      id: '/lol/$accountSlug/patches/'
      path: '/patches'
      fullPath: '/lol/$accountSlug/patches/'
      preLoaderRoute: typeof LolAccountSlugPatchesIndexRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/matches/': {
      id: '/lol/$accountSlug/matches/'
      path: '/matches'
      fullPath: '/lol/$accountSlug/matches/'
      preLoaderRoute: typeof LolAccountSlugMatchesIndexRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/champions/': {
      id: '/lol/$accountSlug/champions/'
      path: '/champions'
      fullPath: '/lol/$accountSlug/champions/'
      preLoaderRoute: typeof LolAccountSlugChampionsIndexRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/patches/$version': {
      id: '/lol/$accountSlug/patches/$version'
      path: '/patches/$version'
      fullPath: '/lol/$accountSlug/patches/$version'
      preLoaderRoute: typeof LolAccountSlugPatchesVersionRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/matches/$matchId': {
      id: '/lol/$accountSlug/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/lol/$accountSlug/matches/$matchId'
      preLoaderRoute: typeof LolAccountSlugMatchesMatchIdRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/champions/$championKey': {
      id: '/lol/$accountSlug/champions/$championKey'
      path: '/champions/$championKey'
      fullPath: '/lol/$accountSlug/champions/$championKey'
      preLoaderRoute: typeof LolAccountSlugChampionsChampionKeyRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/matches/$matchId/': {
      id: '/lol/$accountSlug/matches/$matchId/'
      path: '/'
      fullPath: '/lol/$accountSlug/matches/$matchId/'
      preLoaderRoute: typeof LolAccountSlugMatchesMatchIdIndexRouteImport
      parentRoute: typeof LolAccountSlugMatchesMatchIdRoute
    }
    '/lol/$accountSlug/matches/$matchId/your-game': {
      id: '/lol/$accountSlug/matches/$matchId/your-game'
      path: '/your-game'
      fullPath: '/lol/$accountSlug/matches/$matchId/your-game'
      preLoaderRoute: typeof LolAccountSlugMatchesMatchIdYourGameRouteImport
      parentRoute: typeof LolAccountSlugMatchesMatchIdRoute
    }
    '/lol/$accountSlug/matches/$matchId/timeline': {
      id: '/lol/$accountSlug/matches/$matchId/timeline'
      path: '/timeline'
      fullPath: '/lol/$accountSlug/matches/$matchId/timeline'
      preLoaderRoute: typeof LolAccountSlugMatchesMatchIdTimelineRouteImport
      parentRoute: typeof LolAccountSlugMatchesMatchIdRoute
    }
    '/lol/$accountSlug/matches/$matchId/recap': {
      id: '/lol/$accountSlug/matches/$matchId/recap'
      path: '/recap'
      fullPath: '/lol/$accountSlug/matches/$matchId/recap'
      preLoaderRoute: typeof LolAccountSlugMatchesMatchIdRecapRouteImport
      parentRoute: typeof LolAccountSlugMatchesMatchIdRoute
    }
  }
}

interface SteamRouteChildren {
  SteamAchievementsRoute: typeof SteamAchievementsRoute
  SteamLibraryRoute: typeof SteamLibraryRoute
  SteamWishlistRoute: typeof SteamWishlistRoute
  SteamIndexRoute: typeof SteamIndexRoute
  SteamAchievementsSignatureRoute: typeof SteamAchievementsSignatureRoute
  SteamGameAppidRoute: typeof SteamGameAppidRoute
}

const SteamRouteChildren: SteamRouteChildren = {
  SteamAchievementsRoute: SteamAchievementsRoute,
  SteamLibraryRoute: SteamLibraryRoute,
  SteamWishlistRoute: SteamWishlistRoute,
  SteamIndexRoute: SteamIndexRoute,
  SteamAchievementsSignatureRoute: SteamAchievementsSignatureRoute,
  SteamGameAppidRoute: SteamGameAppidRoute,
}

const SteamRouteWithChildren = SteamRoute._addFileChildren(SteamRouteChildren)

interface LolAccountSlugMatchesMatchIdRouteChildren {
  LolAccountSlugMatchesMatchIdRecapRoute: typeof LolAccountSlugMatchesMatchIdRecapRoute
  LolAccountSlugMatchesMatchIdTimelineRoute: typeof LolAccountSlugMatchesMatchIdTimelineRoute
  LolAccountSlugMatchesMatchIdYourGameRoute: typeof LolAccountSlugMatchesMatchIdYourGameRoute
  LolAccountSlugMatchesMatchIdIndexRoute: typeof LolAccountSlugMatchesMatchIdIndexRoute
}

const LolAccountSlugMatchesMatchIdRouteChildren: LolAccountSlugMatchesMatchIdRouteChildren =
  {
    LolAccountSlugMatchesMatchIdRecapRoute:
      LolAccountSlugMatchesMatchIdRecapRoute,
    LolAccountSlugMatchesMatchIdTimelineRoute:
      LolAccountSlugMatchesMatchIdTimelineRoute,
    LolAccountSlugMatchesMatchIdYourGameRoute:
      LolAccountSlugMatchesMatchIdYourGameRoute,
    LolAccountSlugMatchesMatchIdIndexRoute:
      LolAccountSlugMatchesMatchIdIndexRoute,
  }

const LolAccountSlugMatchesMatchIdRouteWithChildren =
  LolAccountSlugMatchesMatchIdRoute._addFileChildren(
    LolAccountSlugMatchesMatchIdRouteChildren,
  )

interface LolAccountSlugRouteChildren {
  LolAccountSlugLiveRoute: typeof LolAccountSlugLiveRoute
  LolAccountSlugRecapRoute: typeof LolAccountSlugRecapRoute
  LolAccountSlugTrendsRoute: typeof LolAccountSlugTrendsRoute
  LolAccountSlugIndexRoute: typeof LolAccountSlugIndexRoute
  LolAccountSlugChampionsChampionKeyRoute: typeof LolAccountSlugChampionsChampionKeyRoute
  LolAccountSlugMatchesMatchIdRoute: typeof LolAccountSlugMatchesMatchIdRouteWithChildren
  LolAccountSlugPatchesVersionRoute: typeof LolAccountSlugPatchesVersionRoute
  LolAccountSlugChampionsIndexRoute: typeof LolAccountSlugChampionsIndexRoute
  LolAccountSlugMatchesIndexRoute: typeof LolAccountSlugMatchesIndexRoute
  LolAccountSlugPatchesIndexRoute: typeof LolAccountSlugPatchesIndexRoute
}

const LolAccountSlugRouteChildren: LolAccountSlugRouteChildren = {
  LolAccountSlugLiveRoute: LolAccountSlugLiveRoute,
  LolAccountSlugRecapRoute: LolAccountSlugRecapRoute,
  LolAccountSlugTrendsRoute: LolAccountSlugTrendsRoute,
  LolAccountSlugIndexRoute: LolAccountSlugIndexRoute,
  LolAccountSlugChampionsChampionKeyRoute:
    LolAccountSlugChampionsChampionKeyRoute,
  LolAccountSlugMatchesMatchIdRoute:
    LolAccountSlugMatchesMatchIdRouteWithChildren,
  LolAccountSlugPatchesVersionRoute: LolAccountSlugPatchesVersionRoute,
  LolAccountSlugChampionsIndexRoute: LolAccountSlugChampionsIndexRoute,
  LolAccountSlugMatchesIndexRoute: LolAccountSlugMatchesIndexRoute,
  LolAccountSlugPatchesIndexRoute: LolAccountSlugPatchesIndexRoute,
}

const LolAccountSlugRouteWithChildren = LolAccountSlugRoute._addFileChildren(
  LolAccountSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatusRoute: StatusRoute,
  SteamRoute: SteamRouteWithChildren,
  LolAccountSlugRoute: LolAccountSlugRouteWithChildren,
  LolIndexRoute: LolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
