/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SteamRouteImport } from './routes/steam'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LolIndexRouteImport } from './routes/lol/index'
import { Route as LolAccountSlugRouteImport } from './routes/lol/$accountSlug'
import { Route as LolAccountSlugIndexRouteImport } from './routes/lol/$accountSlug/index'
import { Route as LolAccountSlugTrendsRouteImport } from './routes/lol/$accountSlug/trends'
import { Route as LolAccountSlugChampionsRouteImport } from './routes/lol/$accountSlug/champions'
import { Route as LolAccountSlugMatchesIndexRouteImport } from './routes/lol/$accountSlug/matches/index'
import { Route as LolAccountSlugMatchesMatchIdRouteImport } from './routes/lol/$accountSlug/matches/$matchId'

const SteamRoute = SteamRouteImport.update({
  id: '/steam',
  path: '/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LolIndexRoute = LolIndexRouteImport.update({
  id: '/lol/',
  path: '/lol/',
  getParentRoute: () => rootRouteImport,
} as any)
const LolAccountSlugRoute = LolAccountSlugRouteImport.update({
  id: '/lol/$accountSlug',
  path: '/lol/$accountSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LolAccountSlugIndexRoute = LolAccountSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const LolAccountSlugTrendsRoute = LolAccountSlugTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const LolAccountSlugChampionsRoute = LolAccountSlugChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => LolAccountSlugRoute,
} as any)
const LolAccountSlugMatchesIndexRoute =
  LolAccountSlugMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)
const LolAccountSlugMatchesMatchIdRoute =
  LolAccountSlugMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => LolAccountSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/steam': typeof SteamRoute
  '/lol/$accountSlug': typeof LolAccountSlugRouteWithChildren
  '/lol/': typeof LolIndexRoute
  '/lol/$accountSlug/champions': typeof LolAccountSlugChampionsRoute
  '/lol/$accountSlug/trends': typeof LolAccountSlugTrendsRoute
  '/lol/$accountSlug/': typeof LolAccountSlugIndexRoute
  '/lol/$accountSlug/matches/$matchId': typeof LolAccountSlugMatchesMatchIdRoute
  '/lol/$accountSlug/matches/': typeof LolAccountSlugMatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/steam': typeof SteamRoute
  '/lol': typeof LolIndexRoute
  '/lol/$accountSlug/champions': typeof LolAccountSlugChampionsRoute
  '/lol/$accountSlug/trends': typeof LolAccountSlugTrendsRoute
  '/lol/$accountSlug': typeof LolAccountSlugIndexRoute
  '/lol/$accountSlug/matches/$matchId': typeof LolAccountSlugMatchesMatchIdRoute
  '/lol/$accountSlug/matches': typeof LolAccountSlugMatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/steam': typeof SteamRoute
  '/lol/$accountSlug': typeof LolAccountSlugRouteWithChildren
  '/lol/': typeof LolIndexRoute
  '/lol/$accountSlug/champions': typeof LolAccountSlugChampionsRoute
  '/lol/$accountSlug/trends': typeof LolAccountSlugTrendsRoute
  '/lol/$accountSlug/': typeof LolAccountSlugIndexRoute
  '/lol/$accountSlug/matches/$matchId': typeof LolAccountSlugMatchesMatchIdRoute
  '/lol/$accountSlug/matches/': typeof LolAccountSlugMatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/steam'
    | '/lol/$accountSlug'
    | '/lol/'
    | '/lol/$accountSlug/champions'
    | '/lol/$accountSlug/trends'
    | '/lol/$accountSlug/'
    | '/lol/$accountSlug/matches/$matchId'
    | '/lol/$accountSlug/matches/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/steam'
    | '/lol'
    | '/lol/$accountSlug/champions'
    | '/lol/$accountSlug/trends'
    | '/lol/$accountSlug'
    | '/lol/$accountSlug/matches/$matchId'
    | '/lol/$accountSlug/matches'
  id:
    | '__root__'
    | '/'
    | '/steam'
    | '/lol/$accountSlug'
    | '/lol/'
    | '/lol/$accountSlug/champions'
    | '/lol/$accountSlug/trends'
    | '/lol/$accountSlug/'
    | '/lol/$accountSlug/matches/$matchId'
    | '/lol/$accountSlug/matches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SteamRoute: typeof SteamRoute
  LolAccountSlugRoute: typeof LolAccountSlugRouteWithChildren
  LolIndexRoute: typeof LolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/steam': {
      id: '/steam'
      path: '/steam'
      fullPath: '/steam'
      preLoaderRoute: typeof SteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/': {
      id: '/lol/'
      path: '/lol'
      fullPath: '/lol/'
      preLoaderRoute: typeof LolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/$accountSlug': {
      id: '/lol/$accountSlug'
      path: '/lol/$accountSlug'
      fullPath: '/lol/$accountSlug'
      preLoaderRoute: typeof LolAccountSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol/$accountSlug/': {
      id: '/lol/$accountSlug/'
      path: '/'
      fullPath: '/lol/$accountSlug/'
      preLoaderRoute: typeof LolAccountSlugIndexRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/trends': {
      id: '/lol/$accountSlug/trends'
      path: '/trends'
      fullPath: '/lol/$accountSlug/trends'
      preLoaderRoute: typeof LolAccountSlugTrendsRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/champions': {
      id: '/lol/$accountSlug/champions'
      path: '/champions'
      fullPath: '/lol/$accountSlug/champions'
      preLoaderRoute: typeof LolAccountSlugChampionsRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/matches/': {
      id: '/lol/$accountSlug/matches/'
      path: '/matches'
      fullPath: '/lol/$accountSlug/matches/'
      preLoaderRoute: typeof LolAccountSlugMatchesIndexRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
    '/lol/$accountSlug/matches/$matchId': {
      id: '/lol/$accountSlug/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/lol/$accountSlug/matches/$matchId'
      preLoaderRoute: typeof LolAccountSlugMatchesMatchIdRouteImport
      parentRoute: typeof LolAccountSlugRoute
    }
  }
}

interface LolAccountSlugRouteChildren {
  LolAccountSlugChampionsRoute: typeof LolAccountSlugChampionsRoute
  LolAccountSlugTrendsRoute: typeof LolAccountSlugTrendsRoute
  LolAccountSlugIndexRoute: typeof LolAccountSlugIndexRoute
  LolAccountSlugMatchesMatchIdRoute: typeof LolAccountSlugMatchesMatchIdRoute
  LolAccountSlugMatchesIndexRoute: typeof LolAccountSlugMatchesIndexRoute
}

const LolAccountSlugRouteChildren: LolAccountSlugRouteChildren = {
  LolAccountSlugChampionsRoute: LolAccountSlugChampionsRoute,
  LolAccountSlugTrendsRoute: LolAccountSlugTrendsRoute,
  LolAccountSlugIndexRoute: LolAccountSlugIndexRoute,
  LolAccountSlugMatchesMatchIdRoute: LolAccountSlugMatchesMatchIdRoute,
  LolAccountSlugMatchesIndexRoute: LolAccountSlugMatchesIndexRoute,
}

const LolAccountSlugRouteWithChildren = LolAccountSlugRoute._addFileChildren(
  LolAccountSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SteamRoute: SteamRoute,
  LolAccountSlugRoute: LolAccountSlugRouteWithChildren,
  LolIndexRoute: LolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
