/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SteamRouteImport } from './routes/steam'
import { Route as LolRouteImport } from './routes/lol'
import { Route as IndexRouteImport } from './routes/index'

const SteamRoute = SteamRouteImport.update({
  id: '/steam',
  path: '/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const LolRoute = LolRouteImport.update({
  id: '/lol',
  path: '/lol',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lol': typeof LolRoute
  '/steam': typeof SteamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lol': typeof LolRoute
  '/steam': typeof SteamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lol': typeof LolRoute
  '/steam': typeof SteamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lol' | '/steam'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lol' | '/steam'
  id: '__root__' | '/' | '/lol' | '/steam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LolRoute: typeof LolRoute
  SteamRoute: typeof SteamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/steam': {
      id: '/steam'
      path: '/steam'
      fullPath: '/steam'
      preLoaderRoute: typeof SteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lol': {
      id: '/lol'
      path: '/lol'
      fullPath: '/lol'
      preLoaderRoute: typeof LolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LolRoute: LolRoute,
  SteamRoute: SteamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
