-- AlterTable
ALTER TABLE "Match" ADD COLUMN     "damageShare" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "firstBloodKill" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "visionScore" INTEGER NOT NULL DEFAULT 0;
