-- AlterTable
ALTER TABLE "Match" ADD COLUMN     "deathXs" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "deathYs" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "killTimings" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "killXs" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "killYs" INTEGER[] DEFAULT ARRAY[]::INTEGER[];
